In [1]:
import torch
from torch import nn
import torch.nn.functional as F

In [65]:
decoder_layer = nn.TransformerDecoderLayer(d_model=4, nhead=2, dropout=0)
transformer_decoder = nn.TransformerDecoder(decoder_layer=decoder_layer, num_layers=3)
memory = torch.rand(10, 5, 4)

mlp = nn.Linear(4, 1)

In [83]:
tgt1 = torch.rand(8, 5, 4)
tgt2 = tgt1[:6]
tgt3 = torch.cat([tgt2, torch.rand(2, 5, 4)], 0)

inf = float("inf")

tgt1_mask = F.pad(torch.zeros(6,6), (0,2,0,2), "constant", -1e24)
tgt1_mask = tgt1_mask.unsqueeze(0).repeat(2, 1, 1)
tgt1_mask = torch.cat([tgt1_mask.unsqueeze(0), torch.zeros(4, 2, 8, 8)])
tgt1_mask = tgt1_mask.flatten(0, 1)

In [84]:
out1 = mlp(transformer_decoder(tgt1, memory, tgt_mask=tgt1_mask)[:6])

out2 = mlp(transformer_decoder(tgt2, memory, tgt_mask=torch.zeros(6,6)))

out3 = mlp(transformer_decoder(tgt3, memory, tgt_mask=tgt1_mask)[:6])


In [85]:
torch.set_printoptions(precision=10)

In [86]:
out1[:,0,:], out2[:,0,:], out3[:,0,:]

(tensor([[ 1.9686186314e-01],
         [ 1.1771700382e+00],
         [-8.0858796835e-01],
         [ 1.0047802925e+00],
         [-4.7240054607e-01],
         [-4.0441751480e-04]], grad_fn=<SliceBackward0>),
 tensor([[ 1.9686183333e-01],
         [ 1.1771700382e+00],
         [-8.0858790874e-01],
         [ 1.0047802925e+00],
         [-4.7240048647e-01],
         [-4.0441751480e-04]], grad_fn=<SliceBackward0>),
 tensor([[ 1.9686186314e-01],
         [ 1.1771700382e+00],
         [-8.0858796835e-01],
         [ 1.0047802925e+00],
         [-4.7240054607e-01],
         [-4.0441751480e-04]], grad_fn=<SliceBackward0>))