In [7]:
import torch
from torch import nn
import torch.nn.functional as F

torch.set_printoptions(precision=10)

In [41]:
decoder_layer = nn.TransformerDecoderLayer(d_model=4, nhead=2, dropout=0)
transformer_decoder = nn.TransformerDecoder(decoder_layer=decoder_layer, num_layers=3)
memory = torch.rand(10, 1, 4)

mlp = nn.Linear(4, 1)

In [51]:
tgt1 = torch.rand(8, 1, 4)
tgt2 = tgt1[:6]
tgt3 = torch.cat([tgt2, torch.rand(2, 1, 4)], 0)

inf = float("inf")

tgt1_mask = F.pad(torch.zeros(6,6), (0,2,0,2), "constant", -1e32)
tgt1_mask = tgt1_mask.unsqueeze(0).repeat(2, 1, 1)

In [54]:
tgt1_mask2 = torch.zeros(1, 6, dtype=torch.bool)
tgt1_mask2 = F.pad(tgt1_mask2, (0, 2), "constant", True)
tgt1_mask2

tensor([[False, False, False, False, False, False,  True,  True]])

In [55]:
out1 = mlp(transformer_decoder(tgt1, memory, tgt_mask=tgt1_mask)[:6])

out2 = mlp(transformer_decoder(tgt2, memory))

out3 = mlp(transformer_decoder(tgt3, memory, tgt_mask=tgt1_mask)[:6])

print(out1[:,0,:], out2[:,0,:], out3[:,0,:], sep='\n')

tensor([[-0.2519350052],
        [ 1.6431033611],
        [ 1.6271638870],
        [ 0.7572662830],
        [-0.5194247961],
        [ 0.1684416533]], grad_fn=<SliceBackward0>)
tensor([[-0.2519350052],
        [ 1.6431031227],
        [ 1.6271638870],
        [ 0.7572662234],
        [-0.5194247961],
        [ 0.1684416533]], grad_fn=<SliceBackward0>)
tensor([[-0.2519350052],
        [ 1.6431033611],
        [ 1.6271638870],
        [ 0.7572662830],
        [-0.5194247961],
        [ 0.1684416533]], grad_fn=<SliceBackward0>)


In [56]:
out1 = mlp(transformer_decoder(tgt1, memory, tgt_key_padding_mask=tgt1_mask2)[:6])

out2 = mlp(transformer_decoder(tgt2, memory))

out3 = mlp(transformer_decoder(tgt3, memory, tgt_key_padding_mask=tgt1_mask2)[:6])

print(out1[:,0,:], out2[:,0,:], out3[:,0,:], sep='\n')

tensor([[-0.2519350052],
        [ 1.6431033611],
        [ 1.6271638870],
        [ 0.7572662830],
        [-0.5194247961],
        [ 0.1684416533]], grad_fn=<SliceBackward0>)
tensor([[-0.2519350052],
        [ 1.6431031227],
        [ 1.6271638870],
        [ 0.7572662234],
        [-0.5194247961],
        [ 0.1684416533]], grad_fn=<SliceBackward0>)
tensor([[-0.2519350052],
        [ 1.6431033611],
        [ 1.6271638870],
        [ 0.7572662830],
        [-0.5194247961],
        [ 0.1684416533]], grad_fn=<SliceBackward0>)
