In [1]:
%load_ext autoreload
%autoreload 2

In [3]:
import torch
from torch import nn
import torch.nn.functional as F

In [22]:
def loss_fn(y) -> torch.Tensor:
    tgt = torch.rand(3, 1)
    loss = nn.L1Loss()

    output = loss(torch.narrow(y, 0, 0, tgt.size(0)), tgt)

    return output

In [46]:
model1 = nn.Linear(3, 1)

w = model1.state_dict()

model2 = nn.Linear(3, 1)
model2.load_state_dict(w)

<All keys matched successfully>

In [47]:
x1 = torch.rand(5, 3)
x2 = x1[:3]

In [48]:
y1 = model1(x1)
y2 = model2(x2)

y1, y2

(tensor([[0.8017],
         [0.6081],
         [0.9072],
         [0.9016],
         [0.9481]], grad_fn=<AddmmBackward0>),
 tensor([[0.8017],
         [0.6081],
         [0.9072]], grad_fn=<AddmmBackward0>))

In [49]:
optimizer1 = torch.optim.SGD(model1.parameters(), lr=0.001, momentum=0.9)
optimizer2 = torch.optim.SGD(model2.parameters(), lr=0.001, momentum=0.9)

In [59]:
model1.train(True)

y1 = model1(x1)

loss = loss_fn(y1)
loss.backward()

optimizer1.step()

In [60]:
model2.train(True)

y2 = model2(x2)

loss = loss_fn(y2)
loss.backward()

optimizer2.step()

In [61]:
model1.eval()
model2.eval()

y1 = model1(x1)
y2 = model2(x2)

y1, y2

(tensor([[0.8084],
         [0.6122],
         [0.9097],
         [0.9063],
         [0.9534]], grad_fn=<AddmmBackward0>),
 tensor([[0.7933],
         [0.5996],
         [0.8969]], grad_fn=<AddmmBackward0>))