In [50]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [51]:
import torch
from models.model import MulticlassKptsDetector
from models.model import MKDPred

In [52]:
model = MulticlassKptsDetector([3, 4, 5], 64)
x = torch.rand(3, 3, 200, 200)
t = torch.Tensor([0, 1, 2]).int()

pred: MKDPred = model(x, t)

/home/jvillegasl/miniconda3/envs/pytorch/lib/python3.11/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/jvillegasl/miniconda3/envs/pytorch/lib/python3.11/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


pad 2
mask tensor([False, False, False,  True,  True])
pad 1
mask tensor([False, False, False, False,  True])
pad 0
mask tensor([False, False, False, False, False])


/home/jvillegasl/miniconda3/envs/pytorch/lib/python3.11/site-packages/torch/nn/modules/transformer.py:282: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(f"enable_nested_tensor is True, but self.use_nested_tensor is False because {why_not_sparsity_fast_path}")


In [53]:
pred.batch_kpts, pred.masks

(tensor([[[0.4898, 0.5008],
          [0.4871, 0.4967],
          [0.5204, 0.4808],
          [0.4561, 0.4501],
          [0.5312, 0.4964]],
 
         [[0.5603, 0.5496],
          [0.4310, 0.4890],
          [0.4678, 0.4899],
          [0.4118, 0.4900],
          [0.4238, 0.5134]],
 
         [[0.4890, 0.3549],
          [0.4678, 0.3502],
          [0.4925, 0.4229],
          [0.5255, 0.3988],
          [0.4537, 0.4100]]], grad_fn=<SigmoidBackward0>),
 tensor([[False, False, False,  True,  True],
         [False, False, False, False,  True],
         [False, False, False, False, False]]))

In [54]:
pred.unmasked_kpts

[tensor([[0.4898, 0.5008],
         [0.4871, 0.4967],
         [0.5204, 0.4808]], grad_fn=<IndexBackward0>),
 tensor([[0.5603, 0.5496],
         [0.4310, 0.4890],
         [0.4678, 0.4899],
         [0.4118, 0.4900]], grad_fn=<IndexBackward0>),
 tensor([[0.4890, 0.3549],
         [0.4678, 0.3502],
         [0.4925, 0.4229],
         [0.5255, 0.3988],
         [0.4537, 0.4100]], grad_fn=<IndexBackward0>)]

In [55]:
pred.flat_unmasked_kpts

tensor([[0.4898, 0.5008],
        [0.4871, 0.4967],
        [0.5204, 0.4808],
        [0.5603, 0.5496],
        [0.4310, 0.4890],
        [0.4678, 0.4899],
        [0.4118, 0.4900],
        [0.4890, 0.3549],
        [0.4678, 0.3502],
        [0.4925, 0.4229],
        [0.5255, 0.3988],
        [0.4537, 0.4100]], grad_fn=<IndexBackward0>)